import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {framePlan,timing,outputSize,mergePixels} from '../src/sampling.js';import {parseVideo} from '../src/media.js';
test('60 fps 0.1s is exactly six frames; endpoints are not appended',()=>{assert.deepEqual(framePlan(2,31,13,6),[7,13,19,25,31]);assert.deepEqual(framePlan(2,30,13,6),[7,13,19,25]);});
test('all thinning variants retain reference and only use initial frames',()=>{for(const step of [1,3,5,6,11,59])for(const ref of [0,3,27,58]){const base=framePlan(0,60,ref,step);for(const factor of [1,2,3,4]){const selected=framePlan(0,60,ref,step,factor);assert(selected.includes(ref));assert(selected.every(n=>base.includes(n)));assert(selected.every((n,i)=>!i||n-selected[i-1]===step*factor));}}});
test('timescale quantization and irregular timing retain every recorded timestamp',()=>{const samples=Array.from({length:100},(_,i)=>({cts:Math.round(i*1001/60)}));const c=timing(samples,1000);assert(Math.abs(c.fps-59.94)<.1);assert.deepEqual(c.times,samples.map(s=>s.cts/1000));const variable=timing([{cts:0},{cts:10},{cts:30}],1000);assert.deepEqual(variable.times,[0,.01,.03]);assert.equal(variable.variable,true);});
test('size respects memory budget and maximum dimension',()=>{for(const count of [1,10,240]){const s=outputSize(3840,2160,count,960);assert(s.width<=960);assert(s.width*s.height*4*count<81*1024*1024);}});
test('background subtraction overlays moving object only and preserves background',()=>{const bg=new Uint8ClampedArray(400).fill(100);for(let i=3;i<400;i+=4)bg[i]=255;const a=new Uint8ClampedArray(bg),b=new Uint8ClampedArray(bg);a.set([250,0,0,255],40);b.set([0,0,250,255],80);const result=mergePixels(bg,[a,b],30);assert.deepEqual([...result.pixels.slice(40,44)],[250,0,0,255]);assert.deepEqual([...result.pixels.slice(80,84)],[0,0,250,255]);assert.deepEqual([...result.pixels.slice(100,104)],[100,100,100,255]);assert.deepEqual([...bg.slice(40,44)],[100,100,100,255]);});
test('real H264 MP4 has 108 presentation frames and valid codec config',async()=>{const bytes=await readFile(new URL('./fixtures/projectile.mp4',import.meta.url));const media=await parseVideo(new Blob([bytes]));assert.equal(media.clock.ordered.length,108);assert.equal(media.clock.fps,60);assert.match(media.config.codec,/avc1/);assert(media.config.description.byteLength>0);assert.equal(media.rotation,0);const sample=media.mp4.getSample(media.trak,0);assert(sample.data.byteLength>0);assert(sample.is_sync);const selected=framePlan(1,100,25,6);assert(selected.every((n,i)=>!i||media.clock.ordered[n].cts-media.clock.ordered[selected[i-1]].cts===media.track.timescale/10));});

test('normal capture timestamp jitter uses the recorded times without smoothing',()=>{let cts=0;const samples=Array.from({length:121},(_,i)=>{if(i)cts+=16667+[300,-500,800,-600][i%4];return {cts};});const clock=timing(samples,1e6);assert.equal(clock.approximate,false);assert.equal(clock.variable,true);assert.deepEqual(clock.times,samples.map(s=>s.cts/1e6));assert(Math.abs(clock.fps-60)<1);const indices=framePlan(0,120,24,6);assert(indices.every((n,i)=>!i||n-indices[i-1]===6));});
test('dropped frames and variable cadence retain actual gaps',()=>{let cts=0;const samples=Array.from({length:121},(_,i)=>{if(i)cts+=i===30?33334:16667;return {cts};});const clock=timing(samples,1e6);assert.equal(clock.variable,true);assert(Math.abs(clock.times[30]-clock.times[29]-.033334)<1e-12);let irregular=0;const varied=Array.from({length:60},(_,i)=>{if(i)irregular+=i%2?10000:23000;return {cts:irregular};});assert.deepEqual(timing(varied,1e6).times,varied.map(s=>s.cts/1e6));});
test('duplicates remain invalid; genuine recording gaps are not silently compressed',()=>{assert.throws(()=>timing([{cts:0},{cts:0},{cts:20}],1000),/重複/);const samples=Array.from({length:100},(_,i)=>({cts:i*1000+(i>=50?10000:0)}));const clock=timing(samples,60000);assert.equal(clock.variable,true);assert(Math.abs(clock.times[50]-clock.times[49]-11000/60000)<1e-12);});

test('uploaded demo keeps all 216 original frames and passes relaxed timing',async()=>{const bytes=await readFile(new URL('../dist/sample-motion.mp4',import.meta.url));const media=await parseVideo(new Blob([bytes]));assert.equal(media.clock.ordered.length,216);assert(Math.abs(media.clock.fps-30)<.1);assert.equal(media.track.video.width,1280);assert.equal(media.track.video.height,720);});


test('parabolic sample parses the original 112 H264 frames at 120 fps and its selection uses recorded times',async()=>{
 const {samples}=await import('../src/samples.js');const sample=samples.find(x=>x.id==='parabolic-motion');assert(sample);
 const bytes=await readFile(new URL('../dist/'+sample.video,import.meta.url));const media=await parseVideo(new Blob([bytes]));
 assert.equal(media.clock.ordered.length,112);assert.equal(media.clock.fps,120);assert.match(media.config.codec,/avc1/);
 const {indexAtTime,frameTime}=await import('../src/frame-clock.js');const first=indexAtTime(media.clock,sample.range.start),last=indexAtTime(media.clock,sample.range.end),background=indexAtTime(media.clock,sample.range.background);
 assert.equal(first,12);assert.equal(last,78);assert.equal(background,0);
 const indices=framePlan(first,last,first,12);assert.equal(indices.length,6);assert(indices.every((index,i)=>Math.abs(frameTime(media.clock,index)-(.1+i*.1))<1e-12));
 const poster=await readFile(new URL('../dist/'+sample.poster,import.meta.url));assert(poster.length>1000);
});
