import test from 'node:test';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';
import {findCandidates,pickObjectCenter,replaceFrameMark,centersFromMarks} from '../src/tracking.js';import {foregroundMask,drawAnnotations,gridOptions,measuredCenters} from '../src/annotations.js';
const w=240,h=160;
function background(){const a=new Uint8ClampedArray(w*h*4);for(let p=0;p<w*h;p++)a.set([190,190,190,255],p*4);return a;}
function box(a,x,y,ww,hh,color){for(let yy=y;yy<y+hh;yy++)for(let xx=x;xx<x+ww;xx++)a.set([...color,255],(yy*w+xx)*4);}
function picture({stem=false}={}){const bg=background(),frame=new Uint8ClampedArray(bg);box(frame,30,60,12,10,[25,55,95]);box(frame,175,20,35,25,[220,40,30]);if(stem)box(frame,35,40,2,20,[25,55,95]);frame.set([0,0,0,255],4*3);return {bg,frame};}
test('local object center detection ignores speckles and separates a thin stem',()=>{const {bg,frame}=picture({stem:true}),mask=foregroundMask(bg,frame,30,w);assert.equal(findCandidates(mask.pixels,frame,w,h,bg).length,2);const point=pickObjectCenter(bg,frame,w,h,35,64,30);assert.equal(point.source,'object');assert.equal(point.x,35.5);assert.equal(point.y,64.5);});
test('the tapped object is used even when a much larger object is present',()=>{const {bg,frame}=picture();const small=pickObjectCenter(bg,frame,w,h,35,64,30),large=pickObjectCenter(bg,frame,w,h,190,30,30);assert.equal(small.x,35.5);assert.equal(large.x,192);assert.equal(large.y,32);});
test('a tap far from every foreground object stays at the exact tapped position',()=>{const {bg,frame}=picture();const p=pickObjectCenter(bg,frame,w,h,100.125,120.875,30);assert.deepEqual(p,{x:100.125,y:120.875,source:'tap'});});
test('frames have no automatic grids, and each edit changes only its own frame',()=>{const indices=[0,3,6,9];assert(centersFromMarks(indices,[],w,h).every(c=>c.confidence==='unset'));let marks=[];marks=replaceFrameMark(marks,{index:0,mode:'center',x:20.125,y:50.875,source:'object'});const first={...marks[0]};marks=replaceFrameMark(marks,{index:6,mode:'center',x:80.25,y:90.75,source:'object'});marks=replaceFrameMark(marks,{index:6,mode:'center',x:82.625,y:91.125,source:'manual'});assert.deepEqual(marks[0],first);const centers=centersFromMarks(indices,marks,w,h);assert.equal(centers[0].x,20.125);assert.equal(centers[1].confidence,'unset');assert.equal(centers[2].x,82.625);assert.equal(centers[3].confidence,'unset');});
test('skipping and restoring a frame never alters the other selected centers',()=>{let marks=[{index:0,mode:'center',x:25.5,y:44.5},{index:3,mode:'center',x:55.5,y:70.5}];marks=replaceFrameMark(marks,{index:3,mode:'skip'});let centers=centersFromMarks([0,3,6],marks,w,h);assert.equal(centers[0].x,25.5);assert.equal(centers[1].confidence,'skipped');assert.equal(centers[1].x,undefined);assert.equal(measuredCenters(centers).length,1);marks=replaceFrameMark(marks,{index:3,mode:'center',x:50,y:60});centers=centersFromMarks([0,3,6],marks,w,h);assert.equal(measuredCenters(centers).length,2);assert.equal(centers[0].x,25.5);});
test('thinning keeps retained marks exactly and re-expanding restores hidden marks',()=>{const marks=[{index:0,mode:'center',x:20.125,y:44.5},{index:3,mode:'center',x:30.625,y:54.5},{index:6,mode:'skip'},{index:9,mode:'center',x:60.875,y:70.5}];const fine=centersFromMarks([0,3,6,9],marks,w,h),coarse=centersFromMarks([0,6],marks,w,h);assert.deepEqual(coarse,[fine[0],fine[2]]);assert.deepEqual(centersFromMarks([0,3,6,9],marks,w,h),fine);});
test('resolution changes scale the saved coordinate space without re-detecting',()=>{const marks=[{index:3,mode:'center',x:40.125,y:60.875,spaceWidth:240,spaceHeight:160}];const point=centersFromMarks([3],marks,480,320)[0];assert.equal(point.x,80.25);assert.equal(point.y,121.75);assert.equal(marks[0].x,40.125);});
test('guides and timestamps exclude skipped and unmarked frames and do not darken duplicate lines',()=>{const paths=[],texts=[],ctx={save(){},restore(){},beginPath(){},moveTo(x,y){paths.push(['m',x,y]);},lineTo(x,y){paths.push(['l',x,y]);},stroke(){},measureText(){return {width:25};},strokeText(){},fillText(s){texts.push(s);}};drawAnnotations(ctx,[{x:10,y:20,confidence:'manual',time:.1},{x:30,y:20,confidence:'manual',time:.2},{x:99,y:99,confidence:'skipped',time:.3},{index:9,confidence:'unset'}],100,60,{grid:{enabled:true,points:false},labels:true});assert.deepEqual(paths,[['m',10,0],['l',10,60],['m',0,20],['l',100,20],['m',30,0],['l',30,60]]);assert.deepEqual(texts,['0.1000 s','0.2000 s']);assert.equal(gridOptions({color:'invalid',opacity:9}).color,'#ffffff');});
test('the supplied spring-and-bob sample assists each independent tap without filling other frames',t=>{let data;try{data=execFileSync('ffmpeg',['-v','error','-i','dist/sample-motion.mp4','-vf',"select='eq(n,15)+between(n,90,123)*not(mod(n-90,3))',scale=960:540",'-fps_mode','passthrough','-pix_fmt','rgba','-f','rawvideo','pipe:1'],{maxBuffer:40*1024*1024});}catch(e){if(e.code==='ENOENT'){t.skip('FFmpeg is unavailable');return;}throw e;}const width=960,height=540,bytes=width*height*4,bg=data.subarray(0,bytes),clicks=[[414,110],[442,130],[466,131],[486,108],[506,81],[528,72],[552,87],[578,113],[604,131],[628,125],[648,99],[666,78]],indices=clicks.map((_,i)=>90+i*3);let marks=[];for(let i=0;i<clicks.length;i++){const frame=data.subarray((i+1)*bytes,(i+2)*bytes),p=pickObjectCenter(bg,frame,width,height,...clicks[i],30);assert.equal(p.source,'object');assert(Math.hypot(p.x-clicks[i][0],p.y-clicks[i][1])<8);const prior=structuredClone(marks);marks=replaceFrameMark(marks,{index:indices[i],...p,mode:'center'});assert.deepEqual(marks.slice(0,-1),prior);const centers=centersFromMarks(indices,marks,width,height);assert.equal(measuredCenters(centers).length,i+1);}const fixed=centersFromMarks(indices,marks,width,height);for(const sensitivity of [5,80]){pickObjectCenter(bg,data.subarray(bytes,2*bytes),width,height,...clicks[0],sensitivity);assert.deepEqual(centersFromMarks(indices,marks,width,height),fixed);}});
