import {frameTime} from './frame-clock.js';
import {formatSeconds} from './format.js';
export function fitTimelineView(low,high,count,values=[]){
 const max=Math.max(1,count-1),valid=values.filter(Number.isFinite),min=valid.length?Math.min(...valid):null,maxPoint=valid.length?Math.max(...valid):null;
 let span=Math.min(max,Math.max(Math.min(4,max),high-low));
 if(valid.length)span=Math.min(max,Math.max(span,(maxPoint-min)/.9));
 const center=(low+high)/2;low=Math.max(0,Math.min(max-span,center-span/2));
 if(valid.length){const pad=span*.05;low=Math.max(0,Math.min(max-span,Math.min(low,min-pad)));low=Math.max(0,Math.min(max-span,Math.max(low,maxPoint+pad-span)));}
 return {low,high:low+span};
}
export class Timeline{
 constructor(canvas,{getState,onChange,onActive}){this.canvas=canvas;this.getState=getState;this.onChange=onChange;this.onActive=onActive;this.low=0;this.high=1;this.active='start';this.pointers=new Map();this.drag=null;this.colors={start:'#2359db',end:'#df902c',background:'#169f86',reference:'#a05bc6'};this.resize=new ResizeObserver(()=>this.draw());this.resize.observe(canvas);canvas.addEventListener('pointerdown',e=>this.down(e));canvas.addEventListener('pointermove',e=>this.move(e));for(const event of ['pointerup','pointercancel'])canvas.addEventListener(event,e=>this.up(e));canvas.addEventListener('dblclick',()=>this.reset());canvas.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const s=this.getState();this.onChange(this.active,e.key==='Home'?0:e.key==='End'?s.count-1:s[this.active]+(e.key==='ArrowLeft'?-1:1)*(e.shiftKey?10:1));this.draw();}});}
 reset(){this.low=0;this.high=Math.max(1,this.getState().count-1);this.draw();}
 fitSelection(){const s=this.getState(),span=Math.max(1,s.end-s.start);Object.assign(this,fitTimelineView(s.start-span*.06,s.end+span*.06,s.count,[s.start,s.end]));this.draw();}
 setActive(point){this.active=point;this.onActive(point);this.draw();}
 x(index){return 16+(index-this.low)/(this.high-this.low)*(this.canvas.clientWidth-32);}
 index(x){return this.low+(x-16)/(this.canvas.clientWidth-32)*(this.high-this.low);}
 position(e){const r=this.canvas.getBoundingClientRect();return {x:e.clientX-r.left,y:e.clientY-r.top};}
 bound(){const max=Math.max(1,this.getState().count-1);const span=Math.min(max,Math.max(4,this.high-this.low));this.low=Math.max(0,Math.min(max-span,this.low));this.high=this.low+span;}
 pointKeys(){return this.getState().stage==='sampling'?['start','end','background','reference']:['start','end','background'];}
 ensurePointsVisible(){const s=this.getState();Object.assign(this,fitTimelineView(this.low,this.high,s.count,this.pointKeys().map(key=>s[key])));this.draw();}
 zoom(factor){const s=this.getState(),center=Math.max(this.low,Math.min(this.high,s[this.active])),span=(this.high-this.low)*factor;Object.assign(this,fitTimelineView(center-span/2,center+span/2,s.count,this.pointKeys().map(key=>s[key])));this.draw();}
 down(e){e.preventDefault();this.canvas.setPointerCapture(e.pointerId);const p=this.position(e);this.pointers.set(e.pointerId,p);if(this.pointers.size===2){const [a,b]=[...this.pointers.values()];this.drag={type:'pinch',distance:Math.max(1,Math.abs(a.x-b.x)),center:(a.x+b.x)/2,low:this.low,high:this.high};return;}const s=this.getState();const points=s.stage==='sampling'?['reference']:['start','end','background'];const nearest=points.map(k=>({k,d:Math.hypot(this.x(s[k])-p.x,this.y(k)-p.y)})).sort((a,b)=>a.d-b.d)[0];if(nearest?.d<24){this.setActive(nearest.k);this.drag={type:'point'};}else if(this.high-this.low<s.count-1){this.drag={type:'pan',x:p.x,low:this.low,high:this.high};}else{this.drag={type:'point'};this.onChange(this.active,Math.round(this.index(p.x)));}this.draw();}
 move(e){if(!this.pointers.has(e.pointerId)||!this.drag)return;e.preventDefault();const p=this.position(e);this.pointers.set(e.pointerId,p);if(this.drag.type==='pinch'&&this.pointers.size===2){const [a,b]=[...this.pointers.values()],distance=Math.max(1,Math.abs(a.x-b.x)),center=(a.x+b.x)/2,oldspan=this.drag.high-this.drag.low,span=oldspan*this.drag.distance/distance,anchor=this.drag.low+(this.drag.center-16)/(this.canvas.clientWidth-32)*oldspan;this.low=anchor-(center-16)/(this.canvas.clientWidth-32)*span;this.high=this.low+span;this.bound();}else if(this.drag.type==='point'){this.onChange(this.active,Math.round(this.index(p.x)));}else if(this.drag.type==='pan'){const delta=(p.x-this.drag.x)/(this.canvas.clientWidth-32)*(this.drag.high-this.drag.low);this.low=this.drag.low-delta;this.high=this.drag.high-delta;this.bound();}this.draw();}
 up(e){this.pointers.delete(e.pointerId);if(this.pointers.size<2)this.drag=null;}
 y(point){return point==='background'?17:point==='reference'?28:31;}
 draw(){const canvas=this.canvas,w=canvas.clientWidth,h=canvas.clientHeight;if(!w)return;const dpr=Math.min(2,devicePixelRatio||1);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);const s=this.getState();ctx.strokeStyle='#dbe3eb';ctx.lineWidth=5;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(16,28);ctx.lineTo(w-16,28);ctx.stroke();ctx.fillStyle='rgba(35,89,219,.18)';ctx.fillRect(Math.max(16,Math.min(w-16,this.x(s.start))),20,Math.max(0,Math.min(w-16,this.x(s.end))-Math.max(16,this.x(s.start))),16);ctx.strokeStyle='#8daff1';ctx.beginPath();ctx.moveTo(Math.max(16,Math.min(w-16,this.x(s.start))),28);ctx.lineTo(Math.max(16,Math.min(w-16,this.x(s.end))),28);ctx.stroke();if(s.stage==='sampling'&&s.indices){ctx.fillStyle='#2359db';for(const n of s.indices){const x=this.x(n);if(x>=16&&x<=w-16){ctx.beginPath();ctx.arc(x,28,2.5,0,Math.PI*2);ctx.fill();}}}const points=s.stage==='sampling'?['start','end','reference','background']:['start','end','background'];for(const point of points){const x=this.x(s[point]);if(x<12||x>w-12)continue;const y=this.y(point),active=point===this.active;ctx.strokeStyle=this.colors[point];ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(x,28);ctx.lineTo(x,y);ctx.stroke();ctx.fillStyle=this.colors[point];ctx.beginPath();ctx.arc(x,y,active?7:5.5,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.stroke();}ctx.font='12px sans-serif';ctx.fillStyle='#6f7c89';ctx.textBaseline='bottom';ctx.textAlign='left';ctx.fillText(`${formatSeconds(frameTime(s,this.low))} s`,16,h-1);ctx.textAlign='right';ctx.fillText(`${formatSeconds(frameTime(s,this.high))} s`,w-16,h-1);canvas.setAttribute('aria-valuemax',String(s.count-1));canvas.setAttribute('aria-valuenow',String(s[this.active]));canvas.setAttribute('aria-valuetext',`${({start:'開始',end:'終了',background:'背景',reference:'基準'})[this.active]} ${formatSeconds(frameTime(s,s[this.active]))}秒`);}
}
